frase ='Curso em Video Python  '
print(frase)
print((frase[::2]))
print((frase[1::2]))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(frase.count('o'))
print(len(frase))
print(frase.find('deo'))
print(len(frase.strip()))
frase = frase.replace('Python','Android')
print(frase)
print('Curso' in frase)
print(frase.find('Video'))
print(frase.lower().find('video'))
print(frase.split())
divido = frase.split()
print(divido[2])